env:
  CIRRUS_CLONE_DEPTH: "1"
  BOT_TOKEN: "ENCRYPTED[!970c411a816e3831ee594a63a857d4e5f918c4e2353d1e100502d5e7c5610e1f0eeab85b04d6161e6f3fe7806d3444fa!]"
  CHAT_ID: "ENCRYPTED[!23d6f2f3b6d7a0ac5a54ea1b061855a11db8c757b618faece45220c7918bb9a92e16c3484bfe3d331132ef1c9a0be1b6!]"

task:
  name: "Build"
  timeout_in: 120m
  container:
    image: ubuntu
    cpu: 8
    memory: 32G

  Build_script:
     - apt update -y
     - apt install docker.io git -y
     - docker pull navin136/builder:latest
     - docker run -m 30g --oom-kill-disable -it navin136/builder bash rom.sh
